# Generated by Django 4.0.6 on 2022-07-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pic',
            field=models.ImageField(default='static/images/work-img.jpg', upload_to='work_pic'),
        ),
    ]
