# Generated by Django 4.0.6 on 2022-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_work_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pic_cerf',
            field=models.ImageField(default='static/images/work-img.jpg', upload_to='certi'),
        ),
    ]
