# Generated by Django 4.0.6 on 2022-07-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_pic_cerf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='titre_work',
            new_name='titre_blog',
        ),
    ]
